/**********************************************
**Program Filename: DiceRoll.cpp
**Author:Teage Silbert
**Date:6/9/15
**Description:This file serves to randomize
**certain events
**Input: number of faces and dice
**Output: none
**********************************************/

#include <iostream>
#include <ctime>
#include <cstdlib>

#include "DiceRoll.hpp"

using std::cout;
using std::endl;

Roll::Roll(int f, int d)
{
    setFaces(f);
    setDice(d);

}

void Roll::setFaces(int f)
{
    faces = f;
}

void Roll::setDice(int d)
{
    dice = d;
}

/*****************************************
**Function:DiceRoll
**Description: This function returns a
**random value based on how many die and
**how many faces on the die exist
**Parameters: none
**Pre-Conditions: none
**Post-Conditions: number generated by
**number of die and faces is returned
******************************************/
int Roll::rollDie()
{
    //to total the rolls and contain each roll
    int sum = 0;
    int randNum = 0;
    int i = 0;

        for(i; i < dice; i++)
        {
            randNum = 0;
            // generate dice roll and sum total
            randNum = rand() % faces + 1;
            sum +=randNum;
        }

        return sum;
}
